spring.config.import=env_dev.properties

#config datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#config jwt
jwt.secret=${SIGNER_KEY}
jwt.expiration=${VALID_DURATION}
jwt.refreshable-duration=${REFRESHABLE_DURATION}