spring.config.import=env_dev.properties

#config flyway
spring.flyway.schemas=crm

#config datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=${SCHEMA}

#config redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=${REDIS_READ_TIMEOUT}

#config jwt
jwt.secret=${SIGNER_KEY}
jwt.valid-duration=${VALID_DURATION}
jwt.refreshable-duration=${REFRESHABLE_DURATION_DAY}
jwt.refresh-token.cookie.name=refreshToken
jwt.refresh-token.cookie.secure=false