spring.application.name=crm
#config flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.config.import=env.properties

#config datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#config jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refreshable-duration=${REFRESHABLE_DURATION_DAY}

#config cors
app.cors.allowed-origins=http://localhost:5173
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type
app.cors.exposed-headers=Authorization
app.cors.allow-credentials=true
app.cors.max-age=3600
